### ISSUE TITLE
Invalid spring boot version

### ISSUE THREAD

**Issue by gonrocha** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-Third-Edition#12]
Hello everyone,

Spring Boot version 3.0.4 is no longer available via Spring cli. 
The project creation script should be updated to use the 3.1.x or 3.2.x version.

spring init \
--boot-version=3.0.4 \
--type=gradle-project \
--java-version=17 \
--packaging=jar \
--name=product-service \
--package-name=se.magnus.microservices.core.product \
--groupId=se.magnus.microservices.core.product \
--dependencies=actuator,webflux \
--version=1.0.0-SNAPSHOT \
review-service 

Using service at https://start.spring.io
Initializr service call failed using 'https://start.spring.io' - service returned Bad Request: 'Invalid Spring Boot version '3.0.4', Spring Boot compatibility range is >=3.1.0'

**Comment by magnus-larsson** [comment]
Hello, and thanks for pointing out this issue!

I have published a blog post on how to use the source code of this book with Spring Boot 3.1; see [Upgrade to Spring Boot 3.1](https://callistaenterprise.se/blogg/teknik/2023/10/18/microservices-upgrade-to-SpringBoot31/) and the branch `SB3.1`. The branch contains an updated version of `create-projects.bash` that uses Spring Boot 3.1.4.

I have also updated the errata section of the `README.md` file to point out that Spring Initializr no longer supports Spring Boot 3.0.
