### ISSUE TITLE
Typo in Ch.4 when describing how to exit a container?

### ISSUE THREAD

**Issue by jfggdl** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-Third-Edition#3]
In Ch. 4 section "Running our first Docker commands", it has the following text:

"We can leave the container with an exit command and verify that the Ubuntu container no longer **exits** with the docker ps -a command."

I think that "exits" is a typo and should be "exists".

**Comment by magnus-larsson** [comment]
Hello Javier and thanks for reporting this typo! 

I will establish an errata section in the README - file and add a note regarding this.

Regards,
Magnus.
