### ISSUE TITLE
Ch. 22, Helm installation command does not run as-is 

### ISSUE THREAD

**Issue by jfggdl** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-Third-Edition#4]
When attempting to install Helm, I had several problems when copying and pasting the following command in section "Installing tools using apt install":

curl -s https://baltocdn.com/helm/signing.asc | \
  gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null sudo apt-get install apt-transport-https --yes echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/helm.gpg] \
  https://baltocdn.com/helm/stable/debian/ all main" | \
  sudo tee /etc/apt/sources.list.d/helm-stable-debian.list

The "--yes" was being interpreted as part of the Tee command and it would not run.

I had to break it into several command like so:

curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
sudo apt install -y apt-transport-https
echo "deb https://baltocdn.com/helm/stable/debian/ all main" \
  | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt install -y helm

**Comment by magnus-larsson** [comment]
Hello Javier!

I copied the commands from the PDF as:

```
curl -s https://baltocdn.com/helm/signing.asc | \
  gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
sudo apt-get install apt-transport-https --yes
echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/helm.gpg] \
  https://baltocdn.com/helm/stable/debian/ all main" | \
  sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt install -y helm
```

And run them successfully to install Helm on Ubuntu.
It seems like you are missing the line-continuation character, `\`, in your pasted commands.
Could that be your problem?

The commands in the book are just a copy from the product documentation, see https://helm.sh/docs/intro/install/#from-apt-debianubuntu, so they should work fine.

**Comment by magnus-larsson** [comment]
Closing this issue due to a lack of feedback on the proposed solution from the issuer.
