### ISSUE TITLE
Inaccurate description about request response when deleting and using the product-composite microservice in chapter 07, section "Using RabbitMQ without using partitions"

### ISSUE THREAD

**Issue by jfggdl** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-Third-Edition#8]
In chapter 07, section "Using RabbitMQ without using partitions" we have:

...
7. Finally, delete it with the following command:
curl -X DELETE localhost:8080/product-composite/1
8. Try to get the deleted product again. It should result in a **404 - "NotFound" response!**
...

However, when calling delete on the product-composite service we do not get anything because the app it is just sending Delete events to RabbitMQ (as expected). It could not return a 404 NotFound response because there is no actual response from microservice. I think that even in previous sections/chapters where we are no using message broker the microservices are idempotent and 1+ delete operations do not return a 404, but just an http 200 OK. I am not 100% sure of this last statement, though. I hope this helps!

**Comment by magnus-larsson** [comment]
Hello again :-)

Step no 8 says: "_Try to **get** the deleted product again_", mening issue a GET request, not a DELETE request. Like the one in step  no 6:

```
curl -s localhost:8080/product-composite/1 
```

It is expected to return `404`.

Ok?

**Comment by jfggdl** [comment]
@magnus-larsson Thank you for the clarification.

**Comment by magnus-larsson** [comment]
Great, keep on asking questions!
